name: 'build'

on:
  push:
    branches:
      - main
#  pull_request:
#    types:
#      - open
#      - reopen
#      - synchronize
#    branches:
#      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
#          - platform: 'macos-latest' # for Intel based macs.
#            args: '--target x86_64-apple-darwin'
#          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
#            args: ''
#          - platform: 'windows-latest'
#            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0.5.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}